CREATE TABLE cliente (
	id bigint NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(1000) NOT NULL,
	endereco VARCHAR(200) NOT NULL,
	email VARCHAR(200) NOT NULL,
	dt_nascimento DATE NOT NULL,
	cpf VARCHAR(20) NOT NULL
)